---
title: "Mapping the NJ Blue Acres Program and NFIP Claims"
subtitle: "Program Overview, Data Exploration, and Clustering Analysis"
---

## Project Overview

This project was created by Dave Drennan, a graduate student in the University of Pennsylvania's Master of Urban Spatial Analytics Program. Dave is not affiliated with either the State of New Jersey Department of Environmental Protection (DEP) or the Federal Emergency Management Agency (FEMA). This project was created as a final project for two classes - ENVS6611 and MUSA5500 for Fall 2023.  

This project is an exploratory analysis of both the [New Jersey Blue Acres Program](https://dep.nj.gov/blueacres/) and FEMA's [National Flood Insurance Program (NFIP) Redacted Claims](https://www.fema.gov/openfema-data-page/fima-nfip-redacted-claims-v2) data. Additional demographic data is included from the US Census Bureau. The purpose of this analysis is to examine floodprone areas and where mitigation has happened, either through methods of managed retreat or insurance claims. An overview of the Blue Acres Program is provided on page 1, with pages 2, 3, and 4 analyzing the NFIP data before bringing back in the Blue Acres data. Two clustering algorithms are used - DBSCAN for the Blue Acres data and k-means clustering for the NFIP data. Ultimately, the goal of this project was to fill the gap in data visualization and analysis for the Blue Acres Program and NFIP data in New Jersey and examine the spatial and demographic contexts for both. 

## Find out more

The code for this repository is here: [https://github.com/davedrenn/MappingNJBlueAcres](https://github.com/davedrenn/MappingNJBlueAcres).







 
