project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Mapping-NJ-Blue-Acres-Program"
  site-url: "https://davedrenn.github.io/MappingNJBlueAcres/" 
  repo-url: https://github.com/davedrenn/MappingNJBlueAcres 
  repo-actions: [source]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-Dave Drennan, 2023"

  sidebar:
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/davedrenn
        text: "GitHub - davedrenn"    

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Project Overview"
      - section: analysis/index.qmd
        contents:
          - analysis/BlueAcres.ipynb
          - analysis/DataCleaning.ipynb
          - analysis/DataExploration.ipynb
          - analysis/ClaimsKmeans.ipynb

format:
  html:
    highlight-style: solarized
    theme: minty
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




